from __future__ import annotations

from pathlib import Path
from typing import BinaryIO, Callable, Iterable, Protocol


class ArtifactFilesystemPort(Protocol):
    def write_temp(
        self,
        opaque_temp_name: str,
        chunks: Iterable[bytes],
        *,
        max_bytes: int,
        progress_callback: Callable[[int], None] | None = None,
    ) -> tuple[int, str]: ...
    def publish_no_overwrite(self, opaque_temp_name: str, opaque_ref: str) -> None: ...
    def verify_full(self, opaque_ref: str, *, expected_size: int, expected_sha256: str) -> None: ...
    def open_read(self, opaque_ref: str, *, expected_size: int) -> BinaryIO: ...
    def remove_temp(self, opaque_temp_name: str) -> None: ...
    def remove_committed(self, opaque_ref: str) -> None: ...
    def list_blob_refs(self, *, max_refs: int | None = None) -> set[str]: ...
    @property
    def root(self) -> Path: ...
