from __future__ import annotations

from typing import Protocol


class OpsReadinessRepository(Protocol):
    def refresh(self) -> None: ...

    def credential_encryption_available(self) -> bool: ...

    def has_projects(self) -> bool: ...

    def has_active_permission(self) -> bool: ...

    def evidence_ready_project_ids(self) -> list[str]: ...

    def has_tested_model_route(self) -> bool: ...

    def processing_runner_available(self) -> bool: ...
